services:
  - type: web
    name: flask-email-api
    env: python
    buildCommand: ""
    startCommand: python backendpython/app.py
    envVars:
      - key: EMAIL_ADDRESS
        fromEnvVar: EMAIL_ADDRESS
      - key: EMAIL_PASSWORD
        fromEnvVar: EMAIL_PASSWORD
